/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */

// import type { Context } from "./context"
// import type { core } from "nexus"
declare global {
  interface NexusGenCustomInputMethods<TypeName extends string> {
    /**
     * A date-time string at UTC, such as 2007-12-03T10:15:30Z, compliant with the `date-time` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
     */
    // dateTime<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "DateTime";
  }
}
declare global {
  interface NexusGenCustomOutputMethods<TypeName extends string> {
    /**
     * A date-time string at UTC, such as 2007-12-03T10:15:30Z, compliant with the `date-time` format outlined in section 5.6 of the RFC 3339 profile of the ISO 8601 standard for representation of dates and times using the Gregorian calendar.
     */
    // dateTime<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "DateTime";
  }
}

declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  AddToPlaylistInput: {
    // input type
    accountId: string // String!
    owner: string // String!
    playlistId: string // String!
    publishId: string // String!
    stationId: string // String!
  }
  AddToWatchLaterInput: {
    // input type
    accountId: string // String!
    owner: string // String!
    publishId: string // String!
    stationId: string // String!
  }
  CacheSessionInput: {
    // input type
    accountId: string // String!
    address: string // String!
    stationId: string // String!
  }
  CheckPublishPlaylistsInput: {
    // input type
    accountId: string // String!
    owner: string // String!
    publishId: string // String!
    stationId: string // String!
  }
  CommentPublishInput: {
    // input type
    accountId: string // String!
    commentId?: string | null // String
    commentType: NexusGenEnums["CommentType"] // CommentType!
    content: string // String!
    owner: string // String!
    publishId: string // String!
    stationId: string // String!
  }
  CreateDraftBlogInput: {
    // input type
    accountId: string // String!
    creatorId: string // String!
    owner: string // String!
  }
  CreateDraftVideoInput: {
    // input type
    accountId: string // String!
    creatorId: string // String!
    filename: string // String!
    owner: string // String!
  }
  CreatePlayListInput: {
    // input type
    accountId: string // String!
    name: string // String!
    owner: string // String!
    publishId: string // String!
    stationId: string // String!
  }
  CreateStationInput: {
    // input type
    accountId: string // String!
    name: string // String!
    owner: string // String!
    tokenId: number // Int!
  }
  CreateTipInput: {
    // input type
    amount: string // String!
    fee: string // String!
    from: string // String!
    publishId: string // String!
    receiverId: string // String!
    senderId: string // String!
    to: string // String!
  }
  DeletePlaylistInput: {
    // input type
    accountId: string // String!
    owner: string // String!
    playlistId: string // String!
    stationId: string // String!
  }
  DontRecommendInput: {
    // input type
    accountId: string // String!
    owner: string // String!
    stationId: string // String!
    targetId: string // String!
  }
  FetchCommentsByPublishIdInput: {
    // input type
    cursor?: string | null // String
    orderBy?: NexusGenEnums["CommentsOrderBy"] | null // CommentsOrderBy
    publishId: string // String!
    requestorId?: string | null // String
  }
  FetchDontRecommendsInput: {
    // input type
    accountId: string // String!
    cursor?: string | null // String
    owner: string // String!
    requestorId: string // String!
  }
  FetchMyPlaylistsInput: {
    // input type
    accountId: string // String!
    cursor?: string | null // String
    owner: string // String!
    stationId: string // String!
  }
  FetchMyPublishesInput: {
    // input type
    accountId: string // String!
    creatorId: string // String!
    cursor?: string | null // String
    kind: NexusGenEnums["QueryPublishKind"] // QueryPublishKind!
    owner: string // String!
  }
  FetchPlaylistItemsInput: {
    // input type
    accountId: string // String!
    cursor?: string | null // String
    orderBy?: NexusGenEnums["PlaylistOrderBy"] | null // PlaylistOrderBy
    owner: string // String!
    playlistId: string // String!
    stationId: string // String!
  }
  FetchPublishesByCatInput: {
    // input type
    category: NexusGenEnums["Category"] // Category!
    cursor?: string | null // String
    requestorId?: string | null // String
  }
  FetchPublishesInput: {
    // input type
    cursor?: string | null // String
    requestorId?: string | null // String
  }
  FetchShortsInput: {
    // input type
    cursor?: string | null // String
    requestorId?: string | null // String
  }
  FetchStationPublishesInput: {
    // input type
    creatorId: string // String!
    cursor?: string | null // String
    kind?: NexusGenEnums["QueryPublishKind"] | null // QueryPublishKind
    orderBy?: NexusGenEnums["PublishOrderBy"] | null // PublishOrderBy
    requestorId?: string | null // String
  }
  FetchSubCommentsInput: {
    // input type
    commentId: string // String!
    cursor?: string | null // String
    requestorId?: string | null // String
  }
  FetchSuggestedPublishesInput: {
    // input type
    cursor?: string | null // String
    publishId: string // String!
    requestorId?: string | null // String
  }
  FetchWatchLaterInput: {
    // input type
    accountId: string // String!
    cursor?: string | null // String
    orderBy?: NexusGenEnums["PlaylistOrderBy"] | null // PlaylistOrderBy
    owner: string // String!
    stationId: string // String!
  }
  FollowInput: {
    // input type
    accountId: string // String!
    followerId: string // String!
    owner: string // String!
    stationId: string // String!
  }
  GetMyAccountInput: {
    // input type
    accountType: NexusGenEnums["AccountType"] // AccountType!
  }
  GetShortInput: {
    // input type
    publishId: string // String!
    requestorId?: string | null // String
  }
  LikeCommentInput: {
    // input type
    accountId: string // String!
    commentId: string // String!
    owner: string // String!
    publishId: string // String!
    stationId: string // String!
  }
  LikePublishInput: {
    // input type
    accountId: string // String!
    owner: string // String!
    publishId: string // String!
    stationId: string // String!
  }
  MintStationNFTInput: {
    // input type
    accountId: string // String!
    name: string // String!
    to: string // String!
  }
  PlaylistItemStatus: {
    // input type
    isInPlaylist: boolean // Boolean!
    playlistId: string // String!
  }
  QueryByIdInput: {
    // input type
    requestorId?: string | null // String
    targetId: string // String!
  }
  QueryByNameInput: {
    // input type
    name: string // String!
    requestorId?: string | null // String
  }
  RemoveAllWatchLaterInput: {
    // input type
    accountId: string // String!
    owner: string // String!
    stationId: string // String!
  }
  RemoveFromPlaylistInput: {
    // input type
    accountId: string // String!
    owner: string // String!
    playlistId: string // String!
    publishId: string // String!
    stationId: string // String!
  }
  RemoveFromWatchLaterInput: {
    // input type
    accountId: string // String!
    id?: string | null // String
    owner: string // String!
    publishId: string // String!
    stationId: string // String!
  }
  ReportPublishInput: {
    // input type
    accountId: string // String!
    owner: string // String!
    publishId: string // String!
    reason: NexusGenEnums["ReportReason"] // ReportReason!
    stationId: string // String!
  }
  SendTipsInput: {
    // input type
    publishId: string // String!
    qty: number // Int!
    receiverId: string // String!
    senderId: string // String!
  }
  UpdateBlogInput: {
    // input type
    accountId: string // String!
    content?: NexusGenScalars["Json"] | null // Json
    creatorId: string // String!
    filename?: string | null // String
    imageRef?: string | null // String
    imageUrl?: string | null // String
    owner: string // String!
    publishId: string // String!
    tags?: string[] | null // [String!]
    title?: string | null // String
    visibility?: NexusGenEnums["Visibility"] | null // Visibility
  }
  UpdateDisplayNameInput: {
    // input type
    accountId: string // String!
    name: string // String!
    owner: string // String!
    stationId: string // String!
  }
  UpdateImageInput: {
    // input type
    accountId: string // String!
    image: string // String!
    imageRef: string // String!
    owner: string // String!
    stationId: string // String!
  }
  UpdatePlaylistDescriptionInput: {
    // input type
    accountId: string // String!
    description: string // String!
    owner: string // String!
    playlistId: string // String!
    stationId: string // String!
  }
  UpdatePlaylistNameInput: {
    // input type
    accountId: string // String!
    name: string // String!
    owner: string // String!
    playlistId: string // String!
    stationId: string // String!
  }
  UpdatePlaylistsInput: {
    // input type
    accountId: string // String!
    owner: string // String!
    playlists: NexusGenInputs["PlaylistItemStatus"][] // [PlaylistItemStatus!]!
    publishId: string // String!
    stationId: string // String!
  }
  UpdatePreferencesInput: {
    // input type
    accountId: string // String!
    owner: string // String!
    preferences: NexusGenEnums["Category"][] // [Category!]!
    stationId: string // String!
  }
  UpdatePublishInput: {
    // input type
    accountId: string // String!
    contentRef?: string | null // String
    contentURI?: string | null // String
    description?: string | null // String
    kind?: NexusGenEnums["PublishKind"] | null // PublishKind
    owner: string // String!
    primaryCategory?: NexusGenEnums["Category"] | null // Category
    publishId: string // String!
    secondaryCategory?: NexusGenEnums["Category"] | null // Category
    stationId: string // String!
    thumbSource: NexusGenEnums["ThumbSource"] // ThumbSource!
    thumbnail?: string | null // String
    thumbnailRef?: string | null // String
    title?: string | null // String
    visibility?: NexusGenEnums["Visibility"] | null // Visibility
  }
}

export interface NexusGenEnums {
  AccountType: "TRADITIONAL" | "WALLET"
  Category:
    | "AI"
    | "Animals"
    | "Children"
    | "Education"
    | "Entertainment"
    | "Food"
    | "Gaming"
    | "LifeStyle"
    | "Men"
    | "Movies"
    | "Music"
    | "News"
    | "Other"
    | "Programming"
    | "Science"
    | "Sports"
    | "Technology"
    | "Travel"
    | "Vehicles"
    | "Women"
  CommentType: "COMMENT" | "PUBLISH"
  CommentsOrderBy: "counts" | "newest"
  PlaylistOrderBy: "newest" | "oldest"
  PublishKind: "Ads" | "Blog" | "Podcast" | "Short" | "Video"
  PublishOrderBy: "latest" | "popular"
  QueryPublishKind: "ads" | "all" | "blogs" | "podcasts" | "videos"
  ReportReason:
    | "abuse"
    | "adult"
    | "harass"
    | "harmful"
    | "hateful"
    | "mislead"
    | "spam"
    | "terrorism"
    | "violent"
  ThumbSource: "custom" | "generated"
  ThumbnailSource: "custom" | "generated"
  Visibility: "draft" | "private" | "public"
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  DateTime: any
  Json: any
}

export interface NexusGenObjects {
  Account: {
    // root type
    authUid?: string | null // String
    createdAt: NexusGenScalars["DateTime"] // DateTime!
    id: string // ID!
    owner: string // String!
    type: NexusGenEnums["AccountType"] // AccountType!
    updatedAt?: NexusGenScalars["DateTime"] | null // DateTime
  }
  Blog: {
    // root type
    content: NexusGenScalars["Json"] // Json!
    createdAt: NexusGenScalars["DateTime"] // DateTime!
    publishId: string // String!
    updatedAt?: NexusGenScalars["DateTime"] | null // DateTime
  }
  CalculateTipsResult: {
    // root type
    tips: number // Int!
  }
  CheckPublishPlaylistsResponse: {
    // root type
    isInWatchLater: boolean // Boolean!
    items: NexusGenRootTypes["PlaylistItem"][] // [PlaylistItem!]!
    publishId: string // String!
  }
  Comment: {
    // root type
    commentId?: string | null // String
    commentType: NexusGenEnums["CommentType"] // CommentType!
    content: string // String!
    createdAt: NexusGenScalars["DateTime"] // DateTime!
    creatorId: string // String!
    id: string // ID!
    publishId: string // String!
    updatedAt?: NexusGenScalars["DateTime"] | null // DateTime
  }
  CommentDisLike: {
    // root type
    commentId: string // String!
    stationId: string // String!
  }
  CommentEdge: {
    // root type
    cursor?: string | null // String
    node?: NexusGenRootTypes["Comment"] | null // Comment
  }
  CommentLike: {
    // root type
    commentId: string // String!
    stationId: string // String!
  }
  CreateDraftBlogResult: {
    // root type
    id: string // String!
  }
  CreateDraftVideoResult: {
    // root type
    filename?: string | null // String
    id: string // String!
  }
  CreateWalletResult: {
    // root type
    address: string // String!
    uid: string // String!
  }
  DisLike: {
    // root type
    createdAt: NexusGenScalars["DateTime"] // DateTime!
    publishId: string // String!
    stationId: string // String!
  }
  DontRecommend: {
    // root type
    createdAt: NexusGenScalars["DateTime"] // DateTime!
    requestorId: string // String!
    targetId: string // String!
  }
  DontRecommendEdge: {
    // root type
    cursor?: string | null // String
    node?: NexusGenRootTypes["DontRecommend"] | null // DontRecommend
  }
  FetchCommentsResponse: {
    // root type
    edges: NexusGenRootTypes["CommentEdge"][] // [CommentEdge!]!
    pageInfo: NexusGenRootTypes["PageInfo"] // PageInfo!
  }
  FetchDontRecommendsResponse: {
    // root type
    edges: NexusGenRootTypes["DontRecommendEdge"][] // [DontRecommendEdge!]!
    pageInfo: NexusGenRootTypes["PageInfo"] // PageInfo!
  }
  FetchPlaylistItemsResponse: {
    // root type
    edges: NexusGenRootTypes["PlaylistItemEdge"][] // [PlaylistItemEdge!]!
    pageInfo: NexusGenRootTypes["PageInfo"] // PageInfo!
    playlistDescription?: string | null // String
    playlistName: string // String!
  }
  FetchPlaylistsResponse: {
    // root type
    edges: NexusGenRootTypes["PlaylistEdge"][] // [PlaylistEdge!]!
    pageInfo: NexusGenRootTypes["PageInfo"] // PageInfo!
  }
  FetchPreviewPlaylistsResponse: {
    // root type
    edges: NexusGenRootTypes["PreviewPlaylistEdge"][] // [PreviewPlaylistEdge!]!
    pageInfo: NexusGenRootTypes["PageInfo"] // PageInfo!
  }
  FetchPublishesResponse: {
    // root type
    edges: NexusGenRootTypes["PublishEdge"][] // [PublishEdge!]!
    pageInfo: NexusGenRootTypes["PageInfo"] // PageInfo!
  }
  FetchWatchLaterResponse: {
    // root type
    edges: NexusGenRootTypes["WatchLaterEdge"][] // [WatchLaterEdge!]!
    pageInfo: NexusGenRootTypes["PageInfo"] // PageInfo!
  }
  Follow: {
    // root type
    followerId: string // String!
    followingId: string // String!
  }
  GetShortResponse: {
    // root type
    current: NexusGenRootTypes["Publish"] // Publish!
    next?: NexusGenRootTypes["Publish"] | null // Publish
    prev?: NexusGenRootTypes["Publish"] | null // Publish
  }
  Like: {
    // root type
    createdAt: NexusGenScalars["DateTime"] // DateTime!
    publishId: string // String!
    stationId: string // String!
  }
  MintStationNFTResult: {
    // root type
    tokenId: number // Int!
  }
  Mutation: {}
  PageInfo: {
    // root type
    count?: number | null // Int
    endCursor?: string | null // String
    hasNextPage?: boolean | null // Boolean
  }
  PlaybackLink: {
    // root type
    createdAt: NexusGenScalars["DateTime"] // DateTime!
    dash: string // String!
    duration: number // Float!
    hls: string // String!
    id: string // ID!
    preview: string // String!
    publishId: string // String!
    thumbnail: string // String!
    updatedAt?: NexusGenScalars["DateTime"] | null // DateTime
    videoId: string // String!
  }
  Playlist: {
    // root type
    createdAt: NexusGenScalars["DateTime"] // DateTime!
    description?: string | null // String
    id: string // ID!
    name: string // String!
    ownerId: string // String!
  }
  PlaylistEdge: {
    // root type
    cursor?: string | null // String
    node?: NexusGenRootTypes["Playlist"] | null // Playlist
  }
  PlaylistItem: {
    // root type
    createdAt: NexusGenScalars["DateTime"] // DateTime!
    id: string // ID!
    playlistId: string // String!
    publishId: string // String!
  }
  PlaylistItemEdge: {
    // root type
    cursor?: string | null // String
    node?: NexusGenRootTypes["PlaylistItem"] | null // PlaylistItem
  }
  PreviewPlaylist: {
    // root type
    count: number // Int!
    id: string // String!
    lastItem?: NexusGenRootTypes["Publish"] | null // Publish
    name: string // String!
  }
  PreviewPlaylistEdge: {
    // root type
    cursor?: string | null // String
    node?: NexusGenRootTypes["PreviewPlaylist"] | null // PreviewPlaylist
  }
  Publish: {
    // root type
    contentRef?: string | null // String
    contentURI?: string | null // String
    createdAt: NexusGenScalars["DateTime"] // DateTime!
    creatorId: string // String!
    description?: string | null // String
    filename?: string | null // String
    id: string // ID!
    kind?: NexusGenEnums["PublishKind"] | null // PublishKind
    primaryCategory?: NexusGenEnums["Category"] | null // Category
    secondaryCategory?: NexusGenEnums["Category"] | null // Category
    tags: string[] // [String!]!
    thumbSource: NexusGenEnums["ThumbnailSource"] // ThumbnailSource!
    thumbnail?: string | null // String
    thumbnailRef?: string | null // String
    title?: string | null // String
    transcodeError: boolean // Boolean!
    updatedAt?: NexusGenScalars["DateTime"] | null // DateTime
    uploadError: boolean // Boolean!
    uploading: boolean // Boolean!
    views: number // Int!
    visibility: NexusGenEnums["Visibility"] // Visibility!
  }
  PublishEdge: {
    // root type
    cursor?: string | null // String
    node?: NexusGenRootTypes["Publish"] | null // Publish
  }
  Query: {}
  Report: {
    // root type
    createdAt: NexusGenScalars["DateTime"] // DateTime!
    id: string // ID!
    publishId: string // String!
    reason: NexusGenEnums["ReportReason"] // ReportReason!
    submittedById: string // String!
  }
  SendTipsResult: {
    // root type
    amount: string // String!
    fee: string // String!
    from: string // String!
    to: string // String!
  }
  Station: {
    // root type
    accountId: string // String!
    bannerImage?: string | null // String
    bannerImageRef?: string | null // String
    createdAt: NexusGenScalars["DateTime"] // DateTime!
    defaultColor?: string | null // String
    displayName: string // String!
    id: string // ID!
    image?: string | null // String
    imageRef?: string | null // String
    name: string // String!
    owner: string // String!
    preferences: NexusGenEnums["Category"][] // [Category!]!
    tokenId?: number | null // Int
    updatedAt?: NexusGenScalars["DateTime"] | null // DateTime
  }
  Tip: {
    // root type
    amount: string // String!
    createdAt: NexusGenScalars["DateTime"] // DateTime!
    fee: string // String!
    from: string // String!
    id: string // ID!
    publishId: string // String!
    receiverId: string // String!
    senderId: string // String!
    to: string // String!
  }
  WatchLater: {
    // root type
    createdAt: NexusGenScalars["DateTime"] // DateTime!
    id: string // ID!
    publishId: string // String!
    stationId: string // String!
  }
  WatchLaterEdge: {
    // root type
    cursor?: string | null // String
    node?: NexusGenRootTypes["WatchLater"] | null // WatchLater
  }
  WriteResult: {
    // root type
    status: string // String!
  }
}

export interface NexusGenInterfaces {}

export interface NexusGenUnions {}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes &
  NexusGenScalars &
  NexusGenEnums

export interface NexusGenFieldTypes {
  Account: {
    // field return type
    authUid: string | null // String
    createdAt: NexusGenScalars["DateTime"] // DateTime!
    defaultStation: NexusGenRootTypes["Station"] | null // Station
    id: string // ID!
    owner: string // String!
    stations: NexusGenRootTypes["Station"][] // [Station!]!
    type: NexusGenEnums["AccountType"] // AccountType!
    updatedAt: NexusGenScalars["DateTime"] | null // DateTime
  }
  Blog: {
    // field return type
    content: NexusGenScalars["Json"] // Json!
    createdAt: NexusGenScalars["DateTime"] // DateTime!
    publish: NexusGenRootTypes["Publish"] | null // Publish
    publishId: string // String!
    updatedAt: NexusGenScalars["DateTime"] | null // DateTime
  }
  CalculateTipsResult: {
    // field return type
    tips: number // Int!
  }
  CheckPublishPlaylistsResponse: {
    // field return type
    isInWatchLater: boolean // Boolean!
    items: NexusGenRootTypes["PlaylistItem"][] // [PlaylistItem!]!
    publishId: string // String!
  }
  Comment: {
    // field return type
    comment: NexusGenRootTypes["Comment"] | null // Comment
    commentId: string | null // String
    commentType: NexusGenEnums["CommentType"] // CommentType!
    comments: NexusGenRootTypes["Comment"][] // [Comment!]!
    commentsCount: number // Int!
    content: string // String!
    createdAt: NexusGenScalars["DateTime"] // DateTime!
    creator: NexusGenRootTypes["Station"] // Station!
    creatorId: string // String!
    disLiked: boolean | null // Boolean
    disLikes: NexusGenRootTypes["CommentDisLike"][] // [CommentDisLike!]!
    disLikesCount: number // Int!
    id: string // ID!
    liked: boolean | null // Boolean
    likes: NexusGenRootTypes["CommentLike"][] // [CommentLike!]!
    likesCount: number // Int!
    publish: NexusGenRootTypes["Publish"] // Publish!
    publishId: string // String!
    updatedAt: NexusGenScalars["DateTime"] | null // DateTime
  }
  CommentDisLike: {
    // field return type
    comment: NexusGenRootTypes["Comment"] // Comment!
    commentId: string // String!
    station: NexusGenRootTypes["Station"] // Station!
    stationId: string // String!
  }
  CommentEdge: {
    // field return type
    cursor: string | null // String
    node: NexusGenRootTypes["Comment"] | null // Comment
  }
  CommentLike: {
    // field return type
    comment: NexusGenRootTypes["Comment"] // Comment!
    commentId: string // String!
    station: NexusGenRootTypes["Station"] // Station!
    stationId: string // String!
  }
  CreateDraftBlogResult: {
    // field return type
    id: string // String!
  }
  CreateDraftVideoResult: {
    // field return type
    filename: string | null // String
    id: string // String!
  }
  CreateWalletResult: {
    // field return type
    address: string // String!
    uid: string // String!
  }
  DisLike: {
    // field return type
    createdAt: NexusGenScalars["DateTime"] // DateTime!
    publish: NexusGenRootTypes["Publish"] // Publish!
    publishId: string // String!
    station: NexusGenRootTypes["Station"] // Station!
    stationId: string // String!
  }
  DontRecommend: {
    // field return type
    createdAt: NexusGenScalars["DateTime"] // DateTime!
    requestorId: string // String!
    target: NexusGenRootTypes["Station"] // Station!
    targetId: string // String!
  }
  DontRecommendEdge: {
    // field return type
    cursor: string | null // String
    node: NexusGenRootTypes["DontRecommend"] | null // DontRecommend
  }
  FetchCommentsResponse: {
    // field return type
    edges: NexusGenRootTypes["CommentEdge"][] // [CommentEdge!]!
    pageInfo: NexusGenRootTypes["PageInfo"] // PageInfo!
  }
  FetchDontRecommendsResponse: {
    // field return type
    edges: NexusGenRootTypes["DontRecommendEdge"][] // [DontRecommendEdge!]!
    pageInfo: NexusGenRootTypes["PageInfo"] // PageInfo!
  }
  FetchPlaylistItemsResponse: {
    // field return type
    edges: NexusGenRootTypes["PlaylistItemEdge"][] // [PlaylistItemEdge!]!
    pageInfo: NexusGenRootTypes["PageInfo"] // PageInfo!
    playlistDescription: string | null // String
    playlistName: string // String!
  }
  FetchPlaylistsResponse: {
    // field return type
    edges: NexusGenRootTypes["PlaylistEdge"][] // [PlaylistEdge!]!
    pageInfo: NexusGenRootTypes["PageInfo"] // PageInfo!
  }
  FetchPreviewPlaylistsResponse: {
    // field return type
    edges: NexusGenRootTypes["PreviewPlaylistEdge"][] // [PreviewPlaylistEdge!]!
    pageInfo: NexusGenRootTypes["PageInfo"] // PageInfo!
  }
  FetchPublishesResponse: {
    // field return type
    edges: NexusGenRootTypes["PublishEdge"][] // [PublishEdge!]!
    pageInfo: NexusGenRootTypes["PageInfo"] // PageInfo!
  }
  FetchWatchLaterResponse: {
    // field return type
    edges: NexusGenRootTypes["WatchLaterEdge"][] // [WatchLaterEdge!]!
    pageInfo: NexusGenRootTypes["PageInfo"] // PageInfo!
  }
  Follow: {
    // field return type
    follower: NexusGenRootTypes["Station"] // Station!
    followerId: string // String!
    following: NexusGenRootTypes["Station"] // Station!
    followingId: string // String!
  }
  GetShortResponse: {
    // field return type
    current: NexusGenRootTypes["Publish"] // Publish!
    next: NexusGenRootTypes["Publish"] | null // Publish
    prev: NexusGenRootTypes["Publish"] | null // Publish
  }
  Like: {
    // field return type
    createdAt: NexusGenScalars["DateTime"] // DateTime!
    publish: NexusGenRootTypes["Publish"] // Publish!
    publishId: string // String!
    station: NexusGenRootTypes["Station"] // Station!
    stationId: string // String!
  }
  MintStationNFTResult: {
    // field return type
    tokenId: number // Int!
  }
  Mutation: {
    // field return type
    addToNewPlaylist: NexusGenRootTypes["WriteResult"] | null // WriteResult
    addToPlaylist: NexusGenRootTypes["WriteResult"] | null // WriteResult
    addToWatchLater: NexusGenRootTypes["WriteResult"] | null // WriteResult
    cacheSession: NexusGenRootTypes["WriteResult"] // WriteResult!
    calculateTips: NexusGenRootTypes["CalculateTipsResult"] | null // CalculateTipsResult
    comment: NexusGenRootTypes["WriteResult"] | null // WriteResult
    countViews: NexusGenRootTypes["WriteResult"] | null // WriteResult
    createAccount: NexusGenRootTypes["Account"] | null // Account
    createDraftBlog: NexusGenRootTypes["CreateDraftBlogResult"] | null // CreateDraftBlogResult
    createDraftVideo: NexusGenRootTypes["CreateDraftVideoResult"] | null // CreateDraftVideoResult
    createStation: NexusGenRootTypes["Station"] | null // Station
    createTip: NexusGenRootTypes["Tip"] | null // Tip
    deleteAllPlaylistItems: NexusGenRootTypes["WriteResult"] | null // WriteResult
    deletePlaylist: NexusGenRootTypes["WriteResult"] | null // WriteResult
    disLikeComment: NexusGenRootTypes["WriteResult"] | null // WriteResult
    disLikePublish: NexusGenRootTypes["WriteResult"] | null // WriteResult
    dontRecommend: NexusGenRootTypes["WriteResult"] | null // WriteResult
    follow: NexusGenRootTypes["WriteResult"] | null // WriteResult
    likeComment: NexusGenRootTypes["WriteResult"] | null // WriteResult
    likePublish: NexusGenRootTypes["WriteResult"] | null // WriteResult
    mintFirstStationNFT: NexusGenRootTypes["MintStationNFTResult"] | null // MintStationNFTResult
    mintStationNFT: NexusGenRootTypes["MintStationNFTResult"] | null // MintStationNFTResult
    removeAllWatchLater: NexusGenRootTypes["WriteResult"] | null // WriteResult
    removeDontRecommend: NexusGenRootTypes["WriteResult"] | null // WriteResult
    removeFromPlaylist: NexusGenRootTypes["WriteResult"] | null // WriteResult
    removeFromWatchLater: NexusGenRootTypes["WriteResult"] | null // WriteResult
    reportPublish: NexusGenRootTypes["WriteResult"] | null // WriteResult
    sendTips: NexusGenRootTypes["SendTipsResult"] | null // SendTipsResult
    updateBannerImage: NexusGenRootTypes["WriteResult"] | null // WriteResult
    updateBlog: NexusGenRootTypes["WriteResult"] | null // WriteResult
    updateDisplayName: NexusGenRootTypes["WriteResult"] | null // WriteResult
    updatePlaylistDescription: NexusGenRootTypes["WriteResult"] | null // WriteResult
    updatePlaylistName: NexusGenRootTypes["WriteResult"] | null // WriteResult
    updatePlaylists: NexusGenRootTypes["WriteResult"] | null // WriteResult
    updatePreferences: NexusGenRootTypes["WriteResult"] | null // WriteResult
    updateProfileImage: NexusGenRootTypes["WriteResult"] | null // WriteResult
    updatePublish: NexusGenRootTypes["Publish"] | null // Publish
    validateDisplayName: boolean | null // Boolean
    validateName: boolean | null // Boolean
  }
  PageInfo: {
    // field return type
    count: number | null // Int
    endCursor: string | null // String
    hasNextPage: boolean | null // Boolean
  }
  PlaybackLink: {
    // field return type
    createdAt: NexusGenScalars["DateTime"] // DateTime!
    dash: string // String!
    duration: number // Float!
    hls: string // String!
    id: string // ID!
    preview: string // String!
    publish: NexusGenRootTypes["Publish"] | null // Publish
    publishId: string // String!
    thumbnail: string // String!
    updatedAt: NexusGenScalars["DateTime"] | null // DateTime
    videoId: string // String!
  }
  Playlist: {
    // field return type
    createdAt: NexusGenScalars["DateTime"] // DateTime!
    description: string | null // String
    id: string // ID!
    items: NexusGenRootTypes["PlaylistItem"][] // [PlaylistItem!]!
    name: string // String!
    owner: NexusGenRootTypes["Station"] // Station!
    ownerId: string // String!
  }
  PlaylistEdge: {
    // field return type
    cursor: string | null // String
    node: NexusGenRootTypes["Playlist"] | null // Playlist
  }
  PlaylistItem: {
    // field return type
    createdAt: NexusGenScalars["DateTime"] // DateTime!
    id: string // ID!
    playlist: NexusGenRootTypes["Playlist"] // Playlist!
    playlistId: string // String!
    publish: NexusGenRootTypes["Publish"] // Publish!
    publishId: string // String!
  }
  PlaylistItemEdge: {
    // field return type
    cursor: string | null // String
    node: NexusGenRootTypes["PlaylistItem"] | null // PlaylistItem
  }
  PreviewPlaylist: {
    // field return type
    count: number // Int!
    id: string // String!
    lastItem: NexusGenRootTypes["Publish"] | null // Publish
    name: string // String!
  }
  PreviewPlaylistEdge: {
    // field return type
    cursor: string | null // String
    node: NexusGenRootTypes["PreviewPlaylist"] | null // PreviewPlaylist
  }
  Publish: {
    // field return type
    blog: NexusGenRootTypes["Blog"] | null // Blog
    comments: NexusGenRootTypes["Comment"][] // [Comment!]!
    commentsCount: number // Int!
    contentRef: string | null // String
    contentURI: string | null // String
    createdAt: NexusGenScalars["DateTime"] // DateTime!
    creator: NexusGenRootTypes["Station"] // Station!
    creatorId: string // String!
    description: string | null // String
    disLiked: boolean | null // Boolean
    disLikesCount: number // Int!
    dislikes: NexusGenRootTypes["DisLike"][] // [DisLike!]!
    filename: string | null // String
    id: string // ID!
    kind: NexusGenEnums["PublishKind"] | null // PublishKind
    lastComment: NexusGenRootTypes["Comment"] | null // Comment
    liked: boolean | null // Boolean
    likes: NexusGenRootTypes["Like"][] // [Like!]!
    likesCount: number // Int!
    playback: NexusGenRootTypes["PlaybackLink"] | null // PlaybackLink
    primaryCategory: NexusGenEnums["Category"] | null // Category
    secondaryCategory: NexusGenEnums["Category"] | null // Category
    tags: string[] // [String!]!
    thumbSource: NexusGenEnums["ThumbnailSource"] // ThumbnailSource!
    thumbnail: string | null // String
    thumbnailRef: string | null // String
    tips: Array<NexusGenRootTypes["Tip"] | null> // [Tip]!
    tipsCount: number // Int!
    title: string | null // String
    transcodeError: boolean // Boolean!
    updatedAt: NexusGenScalars["DateTime"] | null // DateTime
    uploadError: boolean // Boolean!
    uploading: boolean // Boolean!
    views: number // Int!
    visibility: NexusGenEnums["Visibility"] // Visibility!
  }
  PublishEdge: {
    // field return type
    cursor: string | null // String
    node: NexusGenRootTypes["Publish"] | null // Publish
  }
  Query: {
    // field return type
    checkPublishPlaylists:
      | NexusGenRootTypes["CheckPublishPlaylistsResponse"]
      | null // CheckPublishPlaylistsResponse
    fetchAllVideos: NexusGenRootTypes["FetchPublishesResponse"] | null // FetchPublishesResponse
    fetchCommentsByPublishId: NexusGenRootTypes["FetchCommentsResponse"] | null // FetchCommentsResponse
    fetchDontRecommends: NexusGenRootTypes["FetchDontRecommendsResponse"] | null // FetchDontRecommendsResponse
    fetchMyPlaylists: NexusGenRootTypes["FetchPlaylistsResponse"] | null // FetchPlaylistsResponse
    fetchMyPublishes: NexusGenRootTypes["FetchPublishesResponse"] | null // FetchPublishesResponse
    fetchPlaylistItems: NexusGenRootTypes["FetchPlaylistItemsResponse"] | null // FetchPlaylistItemsResponse
    fetchPreviewPlaylists:
      | NexusGenRootTypes["FetchPreviewPlaylistsResponse"]
      | null // FetchPreviewPlaylistsResponse
    fetchPreviewWatchLater: NexusGenRootTypes["FetchWatchLaterResponse"] | null // FetchWatchLaterResponse
    fetchShorts: NexusGenRootTypes["FetchPublishesResponse"] | null // FetchPublishesResponse
    fetchStationPublishes: NexusGenRootTypes["FetchPublishesResponse"] | null // FetchPublishesResponse
    fetchSubComments: NexusGenRootTypes["FetchCommentsResponse"] | null // FetchCommentsResponse
    fetchSuggestedVideos: NexusGenRootTypes["FetchPublishesResponse"] | null // FetchPublishesResponse
    fetchVideosByCategory: NexusGenRootTypes["FetchPublishesResponse"] | null // FetchPublishesResponse
    fetchWatchLater: NexusGenRootTypes["FetchWatchLaterResponse"] | null // FetchWatchLaterResponse
    getBalance: string // String!
    getMyAccount: NexusGenRootTypes["Account"] | null // Account
    getPublishById: NexusGenRootTypes["Publish"] | null // Publish
    getShort: NexusGenRootTypes["Publish"] | null // Publish
    getStationById: NexusGenRootTypes["Station"] | null // Station
    getStationByName: NexusGenRootTypes["Station"] | null // Station
  }
  Report: {
    // field return type
    createdAt: NexusGenScalars["DateTime"] // DateTime!
    id: string // ID!
    publish: NexusGenRootTypes["Publish"] // Publish!
    publishId: string // String!
    reason: NexusGenEnums["ReportReason"] // ReportReason!
    submittedBy: NexusGenRootTypes["Station"] // Station!
    submittedById: string // String!
  }
  SendTipsResult: {
    // field return type
    amount: string // String!
    fee: string // String!
    from: string // String!
    to: string // String!
  }
  Station: {
    // field return type
    account: NexusGenRootTypes["Account"] // Account!
    accountId: string // String!
    bannerImage: string | null // String
    bannerImageRef: string | null // String
    createdAt: NexusGenScalars["DateTime"] // DateTime!
    defaultColor: string | null // String
    displayName: string // String!
    followersCount: number // Int!
    followingCount: number // Int!
    id: string // ID!
    image: string | null // String
    imageRef: string | null // String
    isFollowing: boolean | null // Boolean
    isOwner: boolean | null // Boolean
    name: string // String!
    owner: string // String!
    preferences: NexusGenEnums["Category"][] // [Category!]!
    publishes: NexusGenRootTypes["Publish"][] // [Publish!]!
    publishesCount: number // Int!
    tokenId: number | null // Int
    updatedAt: NexusGenScalars["DateTime"] | null // DateTime
    watchLater: NexusGenRootTypes["WatchLater"][] // [WatchLater!]!
  }
  Tip: {
    // field return type
    amount: string // String!
    createdAt: NexusGenScalars["DateTime"] // DateTime!
    fee: string // String!
    from: string // String!
    id: string // ID!
    publish: NexusGenRootTypes["Publish"] // Publish!
    publishId: string // String!
    receiver: NexusGenRootTypes["Station"] // Station!
    receiverId: string // String!
    sender: NexusGenRootTypes["Station"] // Station!
    senderId: string // String!
    to: string // String!
  }
  WatchLater: {
    // field return type
    createdAt: NexusGenScalars["DateTime"] // DateTime!
    id: string // ID!
    publish: NexusGenRootTypes["Publish"] // Publish!
    publishId: string // String!
    station: NexusGenRootTypes["Station"] // Station!
    stationId: string // String!
  }
  WatchLaterEdge: {
    // field return type
    cursor: string | null // String
    node: NexusGenRootTypes["WatchLater"] | null // WatchLater
  }
  WriteResult: {
    // field return type
    status: string // String!
  }
}

export interface NexusGenFieldTypeNames {
  Account: {
    // field return type name
    authUid: "String"
    createdAt: "DateTime"
    defaultStation: "Station"
    id: "ID"
    owner: "String"
    stations: "Station"
    type: "AccountType"
    updatedAt: "DateTime"
  }
  Blog: {
    // field return type name
    content: "Json"
    createdAt: "DateTime"
    publish: "Publish"
    publishId: "String"
    updatedAt: "DateTime"
  }
  CalculateTipsResult: {
    // field return type name
    tips: "Int"
  }
  CheckPublishPlaylistsResponse: {
    // field return type name
    isInWatchLater: "Boolean"
    items: "PlaylistItem"
    publishId: "String"
  }
  Comment: {
    // field return type name
    comment: "Comment"
    commentId: "String"
    commentType: "CommentType"
    comments: "Comment"
    commentsCount: "Int"
    content: "String"
    createdAt: "DateTime"
    creator: "Station"
    creatorId: "String"
    disLiked: "Boolean"
    disLikes: "CommentDisLike"
    disLikesCount: "Int"
    id: "ID"
    liked: "Boolean"
    likes: "CommentLike"
    likesCount: "Int"
    publish: "Publish"
    publishId: "String"
    updatedAt: "DateTime"
  }
  CommentDisLike: {
    // field return type name
    comment: "Comment"
    commentId: "String"
    station: "Station"
    stationId: "String"
  }
  CommentEdge: {
    // field return type name
    cursor: "String"
    node: "Comment"
  }
  CommentLike: {
    // field return type name
    comment: "Comment"
    commentId: "String"
    station: "Station"
    stationId: "String"
  }
  CreateDraftBlogResult: {
    // field return type name
    id: "String"
  }
  CreateDraftVideoResult: {
    // field return type name
    filename: "String"
    id: "String"
  }
  CreateWalletResult: {
    // field return type name
    address: "String"
    uid: "String"
  }
  DisLike: {
    // field return type name
    createdAt: "DateTime"
    publish: "Publish"
    publishId: "String"
    station: "Station"
    stationId: "String"
  }
  DontRecommend: {
    // field return type name
    createdAt: "DateTime"
    requestorId: "String"
    target: "Station"
    targetId: "String"
  }
  DontRecommendEdge: {
    // field return type name
    cursor: "String"
    node: "DontRecommend"
  }
  FetchCommentsResponse: {
    // field return type name
    edges: "CommentEdge"
    pageInfo: "PageInfo"
  }
  FetchDontRecommendsResponse: {
    // field return type name
    edges: "DontRecommendEdge"
    pageInfo: "PageInfo"
  }
  FetchPlaylistItemsResponse: {
    // field return type name
    edges: "PlaylistItemEdge"
    pageInfo: "PageInfo"
    playlistDescription: "String"
    playlistName: "String"
  }
  FetchPlaylistsResponse: {
    // field return type name
    edges: "PlaylistEdge"
    pageInfo: "PageInfo"
  }
  FetchPreviewPlaylistsResponse: {
    // field return type name
    edges: "PreviewPlaylistEdge"
    pageInfo: "PageInfo"
  }
  FetchPublishesResponse: {
    // field return type name
    edges: "PublishEdge"
    pageInfo: "PageInfo"
  }
  FetchWatchLaterResponse: {
    // field return type name
    edges: "WatchLaterEdge"
    pageInfo: "PageInfo"
  }
  Follow: {
    // field return type name
    follower: "Station"
    followerId: "String"
    following: "Station"
    followingId: "String"
  }
  GetShortResponse: {
    // field return type name
    current: "Publish"
    next: "Publish"
    prev: "Publish"
  }
  Like: {
    // field return type name
    createdAt: "DateTime"
    publish: "Publish"
    publishId: "String"
    station: "Station"
    stationId: "String"
  }
  MintStationNFTResult: {
    // field return type name
    tokenId: "Int"
  }
  Mutation: {
    // field return type name
    addToNewPlaylist: "WriteResult"
    addToPlaylist: "WriteResult"
    addToWatchLater: "WriteResult"
    cacheSession: "WriteResult"
    calculateTips: "CalculateTipsResult"
    comment: "WriteResult"
    countViews: "WriteResult"
    createAccount: "Account"
    createDraftBlog: "CreateDraftBlogResult"
    createDraftVideo: "CreateDraftVideoResult"
    createStation: "Station"
    createTip: "Tip"
    deleteAllPlaylistItems: "WriteResult"
    deletePlaylist: "WriteResult"
    disLikeComment: "WriteResult"
    disLikePublish: "WriteResult"
    dontRecommend: "WriteResult"
    follow: "WriteResult"
    likeComment: "WriteResult"
    likePublish: "WriteResult"
    mintFirstStationNFT: "MintStationNFTResult"
    mintStationNFT: "MintStationNFTResult"
    removeAllWatchLater: "WriteResult"
    removeDontRecommend: "WriteResult"
    removeFromPlaylist: "WriteResult"
    removeFromWatchLater: "WriteResult"
    reportPublish: "WriteResult"
    sendTips: "SendTipsResult"
    updateBannerImage: "WriteResult"
    updateBlog: "WriteResult"
    updateDisplayName: "WriteResult"
    updatePlaylistDescription: "WriteResult"
    updatePlaylistName: "WriteResult"
    updatePlaylists: "WriteResult"
    updatePreferences: "WriteResult"
    updateProfileImage: "WriteResult"
    updatePublish: "Publish"
    validateDisplayName: "Boolean"
    validateName: "Boolean"
  }
  PageInfo: {
    // field return type name
    count: "Int"
    endCursor: "String"
    hasNextPage: "Boolean"
  }
  PlaybackLink: {
    // field return type name
    createdAt: "DateTime"
    dash: "String"
    duration: "Float"
    hls: "String"
    id: "ID"
    preview: "String"
    publish: "Publish"
    publishId: "String"
    thumbnail: "String"
    updatedAt: "DateTime"
    videoId: "String"
  }
  Playlist: {
    // field return type name
    createdAt: "DateTime"
    description: "String"
    id: "ID"
    items: "PlaylistItem"
    name: "String"
    owner: "Station"
    ownerId: "String"
  }
  PlaylistEdge: {
    // field return type name
    cursor: "String"
    node: "Playlist"
  }
  PlaylistItem: {
    // field return type name
    createdAt: "DateTime"
    id: "ID"
    playlist: "Playlist"
    playlistId: "String"
    publish: "Publish"
    publishId: "String"
  }
  PlaylistItemEdge: {
    // field return type name
    cursor: "String"
    node: "PlaylistItem"
  }
  PreviewPlaylist: {
    // field return type name
    count: "Int"
    id: "String"
    lastItem: "Publish"
    name: "String"
  }
  PreviewPlaylistEdge: {
    // field return type name
    cursor: "String"
    node: "PreviewPlaylist"
  }
  Publish: {
    // field return type name
    blog: "Blog"
    comments: "Comment"
    commentsCount: "Int"
    contentRef: "String"
    contentURI: "String"
    createdAt: "DateTime"
    creator: "Station"
    creatorId: "String"
    description: "String"
    disLiked: "Boolean"
    disLikesCount: "Int"
    dislikes: "DisLike"
    filename: "String"
    id: "ID"
    kind: "PublishKind"
    lastComment: "Comment"
    liked: "Boolean"
    likes: "Like"
    likesCount: "Int"
    playback: "PlaybackLink"
    primaryCategory: "Category"
    secondaryCategory: "Category"
    tags: "String"
    thumbSource: "ThumbnailSource"
    thumbnail: "String"
    thumbnailRef: "String"
    tips: "Tip"
    tipsCount: "Int"
    title: "String"
    transcodeError: "Boolean"
    updatedAt: "DateTime"
    uploadError: "Boolean"
    uploading: "Boolean"
    views: "Int"
    visibility: "Visibility"
  }
  PublishEdge: {
    // field return type name
    cursor: "String"
    node: "Publish"
  }
  Query: {
    // field return type name
    checkPublishPlaylists: "CheckPublishPlaylistsResponse"
    fetchAllVideos: "FetchPublishesResponse"
    fetchCommentsByPublishId: "FetchCommentsResponse"
    fetchDontRecommends: "FetchDontRecommendsResponse"
    fetchMyPlaylists: "FetchPlaylistsResponse"
    fetchMyPublishes: "FetchPublishesResponse"
    fetchPlaylistItems: "FetchPlaylistItemsResponse"
    fetchPreviewPlaylists: "FetchPreviewPlaylistsResponse"
    fetchPreviewWatchLater: "FetchWatchLaterResponse"
    fetchShorts: "FetchPublishesResponse"
    fetchStationPublishes: "FetchPublishesResponse"
    fetchSubComments: "FetchCommentsResponse"
    fetchSuggestedVideos: "FetchPublishesResponse"
    fetchVideosByCategory: "FetchPublishesResponse"
    fetchWatchLater: "FetchWatchLaterResponse"
    getBalance: "String"
    getMyAccount: "Account"
    getPublishById: "Publish"
    getShort: "Publish"
    getStationById: "Station"
    getStationByName: "Station"
  }
  Report: {
    // field return type name
    createdAt: "DateTime"
    id: "ID"
    publish: "Publish"
    publishId: "String"
    reason: "ReportReason"
    submittedBy: "Station"
    submittedById: "String"
  }
  SendTipsResult: {
    // field return type name
    amount: "String"
    fee: "String"
    from: "String"
    to: "String"
  }
  Station: {
    // field return type name
    account: "Account"
    accountId: "String"
    bannerImage: "String"
    bannerImageRef: "String"
    createdAt: "DateTime"
    defaultColor: "String"
    displayName: "String"
    followersCount: "Int"
    followingCount: "Int"
    id: "ID"
    image: "String"
    imageRef: "String"
    isFollowing: "Boolean"
    isOwner: "Boolean"
    name: "String"
    owner: "String"
    preferences: "Category"
    publishes: "Publish"
    publishesCount: "Int"
    tokenId: "Int"
    updatedAt: "DateTime"
    watchLater: "WatchLater"
  }
  Tip: {
    // field return type name
    amount: "String"
    createdAt: "DateTime"
    fee: "String"
    from: "String"
    id: "ID"
    publish: "Publish"
    publishId: "String"
    receiver: "Station"
    receiverId: "String"
    sender: "Station"
    senderId: "String"
    to: "String"
  }
  WatchLater: {
    // field return type name
    createdAt: "DateTime"
    id: "ID"
    publish: "Publish"
    publishId: "String"
    station: "Station"
    stationId: "String"
  }
  WatchLaterEdge: {
    // field return type name
    cursor: "String"
    node: "WatchLater"
  }
  WriteResult: {
    // field return type name
    status: "String"
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    addToNewPlaylist: {
      // args
      input: NexusGenInputs["CreatePlayListInput"] // CreatePlayListInput!
    }
    addToPlaylist: {
      // args
      input: NexusGenInputs["AddToPlaylistInput"] // AddToPlaylistInput!
    }
    addToWatchLater: {
      // args
      input: NexusGenInputs["AddToWatchLaterInput"] // AddToWatchLaterInput!
    }
    cacheSession: {
      // args
      input: NexusGenInputs["CacheSessionInput"] // CacheSessionInput!
    }
    calculateTips: {
      // args
      qty: number // Int!
    }
    comment: {
      // args
      input: NexusGenInputs["CommentPublishInput"] // CommentPublishInput!
    }
    countViews: {
      // args
      publishId: string // String!
    }
    createAccount: {
      // args
      input: NexusGenInputs["GetMyAccountInput"] // GetMyAccountInput!
    }
    createDraftBlog: {
      // args
      input: NexusGenInputs["CreateDraftBlogInput"] // CreateDraftBlogInput!
    }
    createDraftVideo: {
      // args
      input: NexusGenInputs["CreateDraftVideoInput"] // CreateDraftVideoInput!
    }
    createStation: {
      // args
      input: NexusGenInputs["CreateStationInput"] // CreateStationInput!
    }
    createTip: {
      // args
      input: NexusGenInputs["CreateTipInput"] // CreateTipInput!
    }
    deleteAllPlaylistItems: {
      // args
      input: NexusGenInputs["DeletePlaylistInput"] // DeletePlaylistInput!
    }
    deletePlaylist: {
      // args
      input: NexusGenInputs["DeletePlaylistInput"] // DeletePlaylistInput!
    }
    disLikeComment: {
      // args
      input: NexusGenInputs["LikeCommentInput"] // LikeCommentInput!
    }
    disLikePublish: {
      // args
      input: NexusGenInputs["LikePublishInput"] // LikePublishInput!
    }
    dontRecommend: {
      // args
      input: NexusGenInputs["DontRecommendInput"] // DontRecommendInput!
    }
    follow: {
      // args
      input: NexusGenInputs["FollowInput"] // FollowInput!
    }
    likeComment: {
      // args
      input: NexusGenInputs["LikeCommentInput"] // LikeCommentInput!
    }
    likePublish: {
      // args
      input: NexusGenInputs["LikePublishInput"] // LikePublishInput!
    }
    mintFirstStationNFT: {
      // args
      input: NexusGenInputs["MintStationNFTInput"] // MintStationNFTInput!
    }
    mintStationNFT: {
      // args
      input: NexusGenInputs["MintStationNFTInput"] // MintStationNFTInput!
    }
    removeAllWatchLater: {
      // args
      input: NexusGenInputs["RemoveAllWatchLaterInput"] // RemoveAllWatchLaterInput!
    }
    removeDontRecommend: {
      // args
      input: NexusGenInputs["DontRecommendInput"] // DontRecommendInput!
    }
    removeFromPlaylist: {
      // args
      input: NexusGenInputs["RemoveFromPlaylistInput"] // RemoveFromPlaylistInput!
    }
    removeFromWatchLater: {
      // args
      input: NexusGenInputs["RemoveFromWatchLaterInput"] // RemoveFromWatchLaterInput!
    }
    reportPublish: {
      // args
      input: NexusGenInputs["ReportPublishInput"] // ReportPublishInput!
    }
    sendTips: {
      // args
      input: NexusGenInputs["SendTipsInput"] // SendTipsInput!
    }
    updateBannerImage: {
      // args
      input: NexusGenInputs["UpdateImageInput"] // UpdateImageInput!
    }
    updateBlog: {
      // args
      input: NexusGenInputs["UpdateBlogInput"] // UpdateBlogInput!
    }
    updateDisplayName: {
      // args
      input: NexusGenInputs["UpdateDisplayNameInput"] // UpdateDisplayNameInput!
    }
    updatePlaylistDescription: {
      // args
      input: NexusGenInputs["UpdatePlaylistDescriptionInput"] // UpdatePlaylistDescriptionInput!
    }
    updatePlaylistName: {
      // args
      input: NexusGenInputs["UpdatePlaylistNameInput"] // UpdatePlaylistNameInput!
    }
    updatePlaylists: {
      // args
      input: NexusGenInputs["UpdatePlaylistsInput"] // UpdatePlaylistsInput!
    }
    updatePreferences: {
      // args
      input: NexusGenInputs["UpdatePreferencesInput"] // UpdatePreferencesInput!
    }
    updateProfileImage: {
      // args
      input: NexusGenInputs["UpdateImageInput"] // UpdateImageInput!
    }
    updatePublish: {
      // args
      input: NexusGenInputs["UpdatePublishInput"] // UpdatePublishInput!
    }
    validateDisplayName: {
      // args
      name: string // String!
    }
    validateName: {
      // args
      name: string // String!
    }
  }
  Query: {
    checkPublishPlaylists: {
      // args
      input: NexusGenInputs["CheckPublishPlaylistsInput"] // CheckPublishPlaylistsInput!
    }
    fetchAllVideos: {
      // args
      input: NexusGenInputs["FetchPublishesInput"] // FetchPublishesInput!
    }
    fetchCommentsByPublishId: {
      // args
      input: NexusGenInputs["FetchCommentsByPublishIdInput"] // FetchCommentsByPublishIdInput!
    }
    fetchDontRecommends: {
      // args
      input: NexusGenInputs["FetchDontRecommendsInput"] // FetchDontRecommendsInput!
    }
    fetchMyPlaylists: {
      // args
      input: NexusGenInputs["FetchMyPlaylistsInput"] // FetchMyPlaylistsInput!
    }
    fetchMyPublishes: {
      // args
      input: NexusGenInputs["FetchMyPublishesInput"] // FetchMyPublishesInput!
    }
    fetchPlaylistItems: {
      // args
      input: NexusGenInputs["FetchPlaylistItemsInput"] // FetchPlaylistItemsInput!
    }
    fetchPreviewPlaylists: {
      // args
      input: NexusGenInputs["FetchMyPlaylistsInput"] // FetchMyPlaylistsInput!
    }
    fetchPreviewWatchLater: {
      // args
      input: NexusGenInputs["FetchWatchLaterInput"] // FetchWatchLaterInput!
    }
    fetchShorts: {
      // args
      input: NexusGenInputs["FetchShortsInput"] // FetchShortsInput!
    }
    fetchStationPublishes: {
      // args
      input: NexusGenInputs["FetchStationPublishesInput"] // FetchStationPublishesInput!
    }
    fetchSubComments: {
      // args
      input: NexusGenInputs["FetchSubCommentsInput"] // FetchSubCommentsInput!
    }
    fetchSuggestedVideos: {
      // args
      input: NexusGenInputs["FetchSuggestedPublishesInput"] // FetchSuggestedPublishesInput!
    }
    fetchVideosByCategory: {
      // args
      input: NexusGenInputs["FetchPublishesByCatInput"] // FetchPublishesByCatInput!
    }
    fetchWatchLater: {
      // args
      input: NexusGenInputs["FetchWatchLaterInput"] // FetchWatchLaterInput!
    }
    getBalance: {
      // args
      address: string // String!
    }
    getMyAccount: {
      // args
      input: NexusGenInputs["GetMyAccountInput"] // GetMyAccountInput!
    }
    getPublishById: {
      // args
      input: NexusGenInputs["QueryByIdInput"] // QueryByIdInput!
    }
    getShort: {
      // args
      input: NexusGenInputs["GetShortInput"] // GetShortInput!
    }
    getStationById: {
      // args
      input: NexusGenInputs["QueryByIdInput"] // QueryByIdInput!
    }
    getStationByName: {
      // args
      input: NexusGenInputs["QueryByNameInput"] // QueryByNameInput!
    }
  }
}

export interface NexusGenAbstractTypeMembers {}

export interface NexusGenTypeInterfaces {}

export type NexusGenObjectNames = keyof NexusGenObjects

export type NexusGenInputNames = keyof NexusGenInputs

export type NexusGenEnumNames = keyof NexusGenEnums

export type NexusGenInterfaceNames = never

export type NexusGenScalarNames = keyof NexusGenScalars

export type NexusGenUnionNames = never

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never

export type NexusGenAbstractsUsingStrategyResolveType = never

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  // context: Context;
  inputTypes: NexusGenInputs
  rootTypes: NexusGenRootTypes
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars
  argTypes: NexusGenArgTypes
  fieldTypes: NexusGenFieldTypes
  fieldTypeNames: NexusGenFieldTypeNames
  allTypes: NexusGenAllTypes
  typeInterfaces: NexusGenTypeInterfaces
  objectNames: NexusGenObjectNames
  inputNames: NexusGenInputNames
  enumNames: NexusGenEnumNames
  interfaceNames: NexusGenInterfaceNames
  scalarNames: NexusGenScalarNames
  unionNames: NexusGenUnionNames
  allInputTypes:
    | NexusGenTypes["inputNames"]
    | NexusGenTypes["enumNames"]
    | NexusGenTypes["scalarNames"]
  allOutputTypes:
    | NexusGenTypes["objectNames"]
    | NexusGenTypes["enumNames"]
    | NexusGenTypes["unionNames"]
    | NexusGenTypes["interfaceNames"]
    | NexusGenTypes["scalarNames"]
  allNamedTypes:
    | NexusGenTypes["allInputTypes"]
    | NexusGenTypes["allOutputTypes"]
  abstractTypes: NexusGenTypes["interfaceNames"] | NexusGenTypes["unionNames"]
  abstractTypeMembers: NexusGenAbstractTypeMembers
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType
  features: NexusGenFeaturesConfig
}

declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {}
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {}
  interface NexusGenPluginFieldConfig<
    TypeName extends string,
    FieldName extends string
  > {}
  interface NexusGenPluginInputFieldConfig<
    TypeName extends string,
    FieldName extends string
  > {}
  interface NexusGenPluginSchemaConfig {}
  interface NexusGenPluginArgConfig {}
}
